name: Build and Deploy

on:
  push: 
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
            dotnet-version: '8.0.x'
      
      - name: Build Package
        run: dotnet build -c Release
      
      - name: Pack project to NuGet
        run: dotnet pack -c Release
      
      - name: Publish package to NuGet
        run: dotnet nuget push "bin/Release/*.nupkg" -k ${{ secrets.NUGET_SECRET }} -s https://api.nuget.org/v3/index.json